# docker-compose.yml
version: 1.0
services:
  nginx:
    image: nginx:latest
    ports:
     - "80:3000"
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ./app:/usr/share/nginx/www
    command: /bin/bash -c "nginx -g 'daemon off;'"